# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('photo_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('yelp_id', models.TextField(blank=True, null=True)),
                ('business_id', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('split', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('predicted_label', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('predicted_caption_1', models.TextField(blank=True, null=True)),
                ('predicted_caption_2', models.TextField(blank=True, null=True)),
                ('predicted_caption_3', models.TextField(blank=True, null=True)),
                ('predicted_caption_4', models.TextField(blank=True, null=True)),
                ('predicted_caption_5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
    ]
